// <auto-generated />
namespace CRMFacilitoInicial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modifica_actividades : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifica_actividades));
        
        string IMigrationMetadata.Id
        {
            get { return "201807220121540_modifica_actividades"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
